import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = 'http://localhost:5000/api';
const fallbackFoods = [
  { _id: '1', tenMon: 'Cơm gà sốt teriyaki', moTa: 'Gà áp chảo, rau củ theo mùa và cơm thơm', gia: 32000, danhMuc: 'com', danhGiaTB: 4.9, thoiGianChuanBi: 12, tags: ['Bán chạy'], hinhAnh: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=700&q=80' },
  { _id: '2', tenMon: 'Bún bò Huế đặc biệt', moTa: 'Nước dùng đậm vị, giò heo và chả cua', gia: 35000, danhMuc: 'bun', danhGiaTB: 4.8, thoiGianChuanBi: 8, tags: ['Đậm vị'], hinhAnh: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?auto=format&fit=crop&w=700&q=80' },
  { _id: '3', tenMon: 'Cơm chay rau củ', moTa: 'Đậu hũ, nấm và rau củ tươi trong ngày', gia: 28000, danhMuc: 'com', danhGiaTB: 4.7, thoiGianChuanBi: 10, tags: ['Chay', 'Healthy'], hinhAnh: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=700&q=80' },
  { _id: '4', tenMon: 'Phở bò tái lăn', moTa: 'Bánh phở mềm, bò tái và nước dùng hầm xương', gia: 38000, danhMuc: 'pho', danhGiaTB: 4.9, thoiGianChuanBi: 10, tags: ['Yêu thích'], hinhAnh: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=700&q=80' },
  { _id: '5', tenMon: 'Mì Ý bò bằm', moTa: 'Sốt cà chua tự làm, phô mai parmesan', gia: 39000, danhMuc: 'mi', danhGiaTB: 4.6, thoiGianChuanBi: 15, tags: ['Mới'], hinhAnh: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=700&q=80' },
  { _id: '6', tenMon: 'Nước cam tươi', moTa: 'Cam tươi ép, không thêm đường', gia: 18000, danhMuc: 'nuoc', danhGiaTB: 4.8, thoiGianChuanBi: 3, tags: ['Tươi mát'], hinhAnh: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=700&q=80' },
];
const money = (n) => new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 }).format(n);
const statusLabel = { cho_xac_nhan: 'Chờ xác nhận', da_xac_nhan: 'Đã xác nhận', dang_nau: 'Đang nấu', san_sang: 'Sẵn sàng', hoan_tat: 'Hoàn tất', da_huy: 'Đã hủy' };
const vaiTroLabel = { sinh_vien: 'Sinh viên', nhan_vien: 'Nhân viên căn tin', quan_tri: 'Quản trị viên' };

function App() {
  const [page, setPage] = useState('menu'); const [foods, setFoods] = useState(fallbackFoods); const [cart, setCart] = useState([]); const [query, setQuery] = useState(''); const [category, setCategory] = useState('tat_ca'); const [notice, setNotice] = useState(''); const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('smartmeal-user') || 'null')); const [orders, setOrders] = useState(() => JSON.parse(localStorage.getItem('smartmeal-orders') || '[]')); const [lastOrder, setLastOrder] = useState(null); const [thongTinNhan, setThongTinNhan] = useState({ hoTen: user?.hoTen || '', maSinhVien: user?.maSinhVien || '', soDienThoai: '', email: user?.email || '', lop: '' });
  useEffect(() => { fetch(`${API}/mon-an`).then(r => r.ok ? r.json() : null).then(d => d?.monAn?.length && setFoods(d.monAn)).catch(() => {}); }, []);
  const visible = useMemo(() => foods.filter(f => (category === 'tat_ca' || f.danhMuc === category) && f.tenMon.toLowerCase().includes(query.toLowerCase())), [foods, category, query]);
  const add = (food) => { setCart(c => { const item = c.find(x => x._id === food._id); return item ? c.map(x => x._id === food._id ? { ...x, soLuong: x.soLuong + 1 } : x) : [...c, { ...food, soLuong: 1, khauPhan: 'vua' }]; }); setNotice(`Đã thêm ${food.tenMon} vào giỏ`); };
  const changeQty = (id, delta) => setCart(c => c.map(x => x._id === id ? { ...x, soLuong: Math.max(1, x.soLuong + delta) } : x));
  const total = cart.reduce((s, x) => s + x.gia * x.soLuong, 0);
  const submitOrder = async () => { if (!cart.length) return; const token = localStorage.getItem('smartmeal-token'); if (!token) { setNotice('Vui lòng đăng nhập lại trước khi xác nhận đơn.'); setPage('login'); return; } const data = { cacMon: cart.map(x => ({ monAn: x._id, soLuong: x.soLuong, khauPhan: x.khauPhan })), ngayNhan: new Date().toISOString(), gioNhan: '11:45', thongTinNhan }; try { const r = await fetch(`${API}/don-dat`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify(data) }); const d = await r.json(); if (!r.ok) throw new Error(d.thongBao || 'Không thể tạo đơn.'); setOrders(o => { const n = [d.donDat, ...o]; localStorage.setItem('smartmeal-orders', JSON.stringify(n)); return n; }); setLastOrder(d.donDat); setCart([]); setPage('qr'); } catch (error) { setNotice(error.message || 'Không thể kết nối API. Đơn chưa được tạo.'); } };
  const dangNhap = async (email, matKhau) => { const response = await fetch(`${API}/auth/dang-nhap`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, matKhau }) }); const data = await response.json(); if (!response.ok) throw new Error(data.thongBao || 'Không thể đăng nhập.'); setUser(data.nguoiDung); setThongTinNhan(t => ({ ...t, hoTen: data.nguoiDung.hoTen, email: data.nguoiDung.email, maSinhVien: data.nguoiDung.maSinhVien || '' })); localStorage.setItem('smartmeal-user', JSON.stringify(data.nguoiDung)); localStorage.setItem('smartmeal-token', data.token); setNotice(`Đăng nhập với quyền ${vaiTroLabel[data.nguoiDung.vaiTro]}.`); setPage(data.nguoiDung.vaiTro === 'sinh_vien' ? 'menu' : 'dashboard'); };
  const laSinhVien = user?.vaiTro === 'sinh_vien'; const laNhanVien = ['nhan_vien', 'quan_tri'].includes(user?.vaiTro);
  return <><Header page={page} setPage={setPage} user={user} cartCount={cart.reduce((s,x) => s+x.soLuong,0)} onLogout={() => { setUser(null); localStorage.removeItem('smartmeal-user'); localStorage.removeItem('smartmeal-token'); setPage('menu'); }} />{notice && <div className="toast">✓ {notice}<button onClick={() => setNotice('')}>×</button></div>}<main>{page === 'menu' && <Menu foods={visible} add={add} query={query} setQuery={setQuery} category={category} setCategory={setCategory} setPage={setPage}/>} {page === 'cart' && (laSinhVien ? <Cart cart={cart} changeQty={changeQty} setCart={setCart} total={total} submitOrder={submitOrder} thongTinNhan={thongTinNhan} setThongTinNhan={setThongTinNhan} setPage={setPage}/> : <KhongCoQuyen/>)} {page === 'orders' && (laSinhVien ? <Orders orders={orders} setOrders={setOrders} setPage={setPage} setLastOrder={setLastOrder}/> : <KhongCoQuyen/>)} {page === 'qr' && (laSinhVien ? <QR order={lastOrder || orders[0]} setPage={setPage}/> : <KhongCoQuyen/>)} {page === 'dashboard' && (laNhanVien ? <Dashboard user={user}/> : <KhongCoQuyen/>)} {page === 'staff-orders' && (laNhanVien ? <StaffOrders/> : <KhongCoQuyen/>)} {page === 'admin' && (user?.vaiTro === 'quan_tri' ? <AdminPanel/> : <KhongCoQuyen/>)} {page === 'login' && <Login dangNhap={dangNhap} setPage={setPage}/>}</main><Footer/></>;
}
function Header({ page, setPage, user, cartCount, onLogout }) { const laSinhVien = user?.vaiTro === 'sinh_vien'; const laNhanVien = ['nhan_vien', 'quan_tri'].includes(user?.vaiTro); return <header><div className="nav"><button className="brand" onClick={() => setPage(laNhanVien ? 'dashboard' : 'menu')}><span>✦</span> SmartMeal <b>AI</b></button><nav>{(!user || laSinhVien) && <button className={page === 'menu' ? 'active':''} onClick={() => setPage('menu')}>Thực đơn</button>}{laSinhVien && <button className={page === 'orders' ? 'active':''} onClick={() => setPage('orders')}>Đơn của tôi</button>}{laNhanVien && <button className={page === 'dashboard' ? 'active':''} onClick={() => setPage('dashboard')}>Dashboard</button>}{laNhanVien && <button className={page === 'staff-orders' ? 'active':''} onClick={() => setPage('staff-orders')}>Xử lý đơn</button>}{user?.vaiTro === 'quan_tri' && <button className={page === 'admin' ? 'active':''} onClick={() => setPage('admin')}>Quản trị</button>}</nav><div className="nav-actions">{laSinhVien && <button className="cart-icon" onClick={() => setPage('cart')}>🛒{cartCount > 0 && <i>{cartCount}</i>}</button>}{user ? <div className="user-menu"><span className="avatar">{user.hoTen[0]}</span><span className="role-chip">{vaiTroLabel[user.vaiTro]}</span><button onClick={onLogout}>Đăng xuất</button></div> : <button className="outline" onClick={() => setPage('login')}>Đăng nhập</button>}</div></div></header> }
function Menu({ foods, add, query, setQuery, category, setCategory, setPage }) { const cats = [['tat_ca','Tất cả'],['com','Cơm'],['pho','Phở'],['bun','Bún'],['mi','Mì'],['nuoc','Đồ uống']]; return <><section className="hero"><div><p className="eyebrow">CĂN TIN THÔNG MINH</p><h1>Ăn ngon, đúng giờ.<br/><em>Không còn lãng phí.</em></h1><p>Đặt trước suất ăn yêu thích và để SmartMeal AI giúp căn tin chuẩn bị vừa đủ cho bạn.</p><button className="primary" onClick={() => document.getElementById('foods').scrollIntoView({behavior:'smooth'})}>Xem thực đơn <span>→</span></button></div><div className="hero-card"><div className="ai-orb">✦</div><p>AI dự báo hôm nay</p><strong>330 <small>suất ăn</small></strong><div className="progress"><span/></div><label>Đã đặt trước <b>315 suất</b></label><small>Giảm lãng phí thực phẩm mỗi ngày</small></div></section><section className="menu-section" id="foods"><div className="section-heading"><div><p className="eyebrow">THỰC ĐƠN HÔM NAY</p><h2>Chọn món bạn yêu thích</h2></div><button className="link" onClick={() => setPage('dashboard')}>Xem dự báo AI →</button></div><div className="filters"><div className="categories">{cats.map(([key,label]) => <button key={key} className={category===key?'selected':''} onClick={() => setCategory(key)}>{label}</button>)}</div><label className="search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm món ăn..."/></label></div><div className="food-grid">{foods.map(food => <article className="food-card" key={food._id}><div className="food-image"><img src={food.hinhAnh} alt={food.tenMon}/>{food.tags?.[0] && <span>{food.tags[0]}</span>}</div><div className="food-body"><div className="food-meta"><small>{food.danhMuc}</small><small>★ {food.danhGiaTB || '4.8'}</small></div><h3>{food.tenMon}</h3><p>{food.moTa}</p><div className="food-footer"><b>{money(food.gia)}</b><button onClick={() => add(food)}>Thêm <span>+</span></button></div></div></article>)}</div>{!foods.length && <div className="empty">Không có món ăn phù hợp.</div>}</section></> }
function Cart({ cart, changeQty, setCart, total, submitOrder, thongTinNhan, setThongTinNhan, setPage }) {
  const capNhatThongTin = (event) => setThongTinNhan(info => ({ ...info, [event.target.name]: event.target.value }));
  return <section className="cart-page"><div><p className="eyebrow">ĐẶT SUẤT ĂN</p><h1>Giỏ hàng của bạn</h1><p className="muted">Chọn khẩu phần và thời gian nhận món thuận tiện.</p>{cart.length ? <div className="cart-list">{cart.map(x => <article className="cart-row" key={x._id}><img src={x.hinhAnh} alt=""/><div><h3>{x.tenMon}</h3><p>{money(x.gia)}</p><select value={x.khauPhan} onChange={e => setCart(c => c.map(i => i._id === x._id ? {...i, khauPhan:e.target.value} : i))}><option value="nho">Khẩu phần nhỏ</option><option value="vua">Khẩu phần vừa</option><option value="lon">Khẩu phần lớn</option></select></div><div className="quantity"><button onClick={() => changeQty(x._id,-1)}>−</button><b>{x.soLuong}</b><button onClick={() => changeQty(x._id,1)}>+</button></div><strong>{money(x.gia*x.soLuong)}</strong></article>)}</div> : <div className="empty">Giỏ hàng đang trống.<br/><button className="link" onClick={() => setPage('menu')}>Chọn món ngay →</button></div>}</div><aside className="checkout"><h3>Tóm tắt đơn hàng</h3><div className="pickup"><span>◷</span><div><b>Nhận món hôm nay</b><p>11:45 — 12:00 · Quầy A</p></div></div><form onSubmit={event => { event.preventDefault(); submitOrder(); }}><div className="recipient-form"><h4>Thông tin nhận món</h4><p>Nhân viên sẽ dùng thông tin này để đối chiếu tại quầy.</p><div className="recipient-grid"><label>Họ và tên<input name="hoTen" value={thongTinNhan.hoTen} onChange={capNhatThongTin} required/></label><label>Mã số sinh viên<input name="maSinhVien" value={thongTinNhan.maSinhVien} onChange={capNhatThongTin} required/></label><label>Số điện thoại<input name="soDienThoai" value={thongTinNhan.soDienThoai} onChange={capNhatThongTin} type="tel" required/></label><label>Email<input name="email" value={thongTinNhan.email} onChange={capNhatThongTin} type="email" required/></label><label className="wide">Lớp<input name="lop" value={thongTinNhan.lop} onChange={capNhatThongTin} placeholder="Ví dụ: CNTT K48A" required/></label></div></div><div className="total"><span>Tạm tính</span><b>{money(total)}</b><span>Phí dịch vụ</span><b>0 ₫</b><strong>Tổng cộng <em>{money(total)}</em></strong></div><button className="primary full" disabled={!cart.length}>Xác nhận đặt món →</button></form><p className="safe">🔒 Thông tin chỉ dùng để xác nhận khi nhận món</p></aside></section>
}
function Orders({orders, setOrders, setPage, setLastOrder}) { const [loi,setLoi]=useState(''); useEffect(()=>{const token=localStorage.getItem('smartmeal-token'); if(!token)return; fetch(`${API}/don-dat`,{headers:{Authorization:`Bearer ${token}`}}).then(async r=>({ok:r.ok,data:await r.json()})).then(({ok,data})=>{if(!ok)throw new Error(data.thongBao);setOrders(data.donDat);localStorage.setItem('smartmeal-orders',JSON.stringify(data.donDat));}).catch(error=>setLoi(error.message||'Không thể tải đơn hàng.'));},[setOrders]); return <section className="orders"><p className="eyebrow">LỊCH SỬ ĐẶT MÓN</p><h1>Đơn hàng của tôi</h1>{loi&&<p className="api-error">{loi}</p>}<div className="orders-list">{orders.length ? orders.map(o => <article key={o._id}><div><span className="order-icon">🍱</span><div><h3>{o.maDon}</h3><p>{new Date(o.ngayNhan || o.createdAt).toLocaleDateString('vi-VN')} · {o.gioNhan} · {o.cacMon.map(m=>m.tenMon).join(', ')}</p></div></div><span className={`status ${o.trangThai}`}>{statusLabel[o.trangThai]}</span><b>{money(o.tongTien)}</b><button className="outline" onClick={() => {setLastOrder(o);setPage('qr')}}>QR nhận món</button></article>) : <div className="empty">Bạn chưa có đơn hàng nào.</div>}</div></section> }
function QR({order, setPage}) { return <section className="qr-page">{order ? <div className="qr-card"><p className="eyebrow">NHẬN MÓN TẠI QUẦY</p><h1>Mã QR đơn hàng</h1><p>Đưa mã này cho nhân viên khi nhận món.</p><div className="qr"><div className="qr-pattern">{Array.from({length:100},(_,i)=><i key={i} className={(i*13+i*i)%7<3?'on':''}/>)}</div><span>✦</span></div><h2>{order.maDon}</h2><div className="qr-details"><span>👤 <b>{order.thongTinNhan?.hoTen}</b> · {order.thongTinNhan?.maSinhVien}</span><span>⏱ Nhận món <b>{order.gioNhan || '11:45'} hôm nay</b></span><span>📍 Quầy A · Căn tin trung tâm</span></div><button className="primary" onClick={()=>setPage('orders')}>Xem đơn hàng của tôi</button></div> : <div className="empty">Không tìm thấy đơn hàng.</div>}</section> }
function KhongCoQuyen(){return <section className="access-denied"><div><span>🔒</span><h1>Bạn không có quyền truy cập</h1><p>Chức năng này chỉ hiển thị cho vai trò phù hợp.</p></div></section>}
function StaffOrders(){const [donDat,setDonDat]=useState([]);const [loi,setLoi]=useState('');const token=localStorage.getItem('smartmeal-token');const taiDon=()=>fetch(`${API}/don-dat`,{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.json()).then(d=>d.thanhCong?setDonDat(d.donDat):setLoi(d.thongBao)).catch(()=>setLoi('Không thể kết nối API.'));useEffect(taiDon,[]);const capNhat=async(id,trangThai)=>{const r=await fetch(`${API}/don-dat/${id}/trang-thai`,{method:'PUT',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({trangThai})});if(r.ok)taiDon();};return <section className="orders staff-orders"><p className="eyebrow">CĂN TIN · VẬN HÀNH</p><h1>Xử lý đơn đặt món</h1><p className="muted">Xác nhận, chuyển bếp và báo sẵn sàng cho sinh viên.</p>{loi&&<p className="api-error">{loi}</p>}<div className="orders-list">{donDat.length?donDat.map(o=><article key={o._id}><div><span className="order-icon">🍱</span><div><h3>{o.maDon} · {o.thongTinNhan?.hoTen}</h3><p>{o.thongTinNhan?.maSinhVien} · {o.thongTinNhan?.lop} · {o.cacMon.map(m=>m.tenMon).join(', ')}</p></div></div><span className={`status ${o.trangThai}`}>{statusLabel[o.trangThai]}</span><select aria-label="Trạng thái đơn" value={o.trangThai} onChange={e=>capNhat(o._id,e.target.value)}><option value="cho_xac_nhan">Chờ xác nhận</option><option value="da_xac_nhan">Đã xác nhận</option><option value="dang_nau">Đang nấu</option><option value="san_sang">Sẵn sàng</option><option value="hoan_tat">Hoàn tất</option></select></article>):<div className="empty">Chưa có đơn để xử lý.</div>}</div></section>}
function AdminPanel(){return <section className="dashboard admin-panel"><p className="eyebrow">QUẢN TRỊ HỆ THỐNG</p><h1>Trung tâm quản trị</h1><p className="muted">Quản trị viên có toàn quyền xem dữ liệu vận hành và cấu hình hệ thống.</p><div className="admin-grid"><article><span>👥</span><h3>Tài khoản & phân quyền</h3><p>Quản lý tài khoản sinh viên, nhân viên và quản trị viên qua API người dùng.</p></article><article><span>🍲</span><h3>Danh mục món ăn</h3><p>Thêm, sửa, xóa món ăn; kiểm soát món còn phục vụ.</p></article><article><span>✦</span><h3>Báo cáo dự báo AI</h3><p>Xem lịch sử, sai số và hiệu quả của dữ liệu dự báo.</p></article></div></section>}
function Dashboard(){ const bars=[320,290,350,310,338,220,195]; return <section className="dashboard"><div className="dash-heading"><div><p className="eyebrow">CANTEEN INTELLIGENCE</p><h1>Dashboard hôm nay</h1><p>Thứ Sáu, 10 tháng 7, 2026 · Dữ liệu cập nhật theo thời gian thực</p></div><button className="outline">↓ Xuất báo cáo</button></div><div className="stats"><Stat icon="🛍" label="Đã đặt trước" value="315" note="↑ 12% so với hôm qua" color="green"/><Stat icon="✦" label="AI dự đoán" value="330" note="Độ chính xác 94.2%" color="purple"/><Stat icon="♨" label="Đề xuất chuẩn bị" value="340" note="Có 10 suất dự phòng" color="orange"/><Stat icon="♻" label="Dư ước tính" value="10" note="Giảm 68% so với trước" color="blue"/></div><div className="analytics"><article className="chart-card"><div><h3>Xu hướng đặt suất</h3><p>Số suất đặt trước trong tuần này</p></div><div className="bar-chart">{bars.map((v,i)=><div key={v}><span style={{height:`${v/4}px`}}>{i===4&&<b>338</b>}</span><small>{['T2','T3','T4','T5','T6','T7','CN'][i]}</small></div>)}</div></article><article className="prediction"><p className="eyebrow">GỢI Ý AI</p><h3>Chuẩn bị thực phẩm</h3><div className="dish-pred"><span>🍗</span><div><b>Cơm gà sốt teriyaki</b><p>AI dự đoán 128 suất</p></div><strong>134<br/><small>suất</small></strong></div><div className="dish-pred"><span>🍜</span><div><b>Bún bò Huế đặc biệt</b><p>AI dự đoán 96 suất</p></div><strong>100<br/><small>suất</small></strong></div><button className="link">Xem toàn bộ đề xuất →</button></article></div></section> }
function Stat({icon,label,value,note,color}) { return <article className={`stat ${color}`}><span>{icon}</span><p>{label}</p><strong>{value}</strong><small>{note}</small></article> }
function Login({dangNhap,setPage}){const [email,setEmail]=useState('');const [matKhau,setMatKhau]=useState('');const [loi,setLoi]=useState('');const submit=async(e)=>{e.preventDefault();setLoi('');try{await dangNhap(email,matKhau)}catch(error){setLoi(error.message)}};return <section className="login"><form onSubmit={submit}><div className="login-mark">✦</div><p className="eyebrow">SMARTMEAL AI</p><h1>Chào mừng trở lại</h1><p>Đăng nhập để sử dụng đúng quyền được cấp.</p><label>Email trường<input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="tenban@sv.edu.vn" required/></label><label>Mật khẩu<input value={matKhau} onChange={e=>setMatKhau(e.target.value)} type="password" placeholder="••••••••" required/></label>{loi&&<p className="api-error">{loi}</p>}<button className="primary full">Đăng nhập</button><p className="demo">Tài khoản mẫu: student@smartmeal.vn, staff@smartmeal.vn hoặc admin@smartmeal.vn.</p><button type="button" className="link" onClick={()=>setPage('menu')}>← Quay lại thực đơn</button></form></section> }
function Footer(){return <footer><div><button className="brand"><span>✦</span> SmartMeal <b>AI</b></button><p>Đặt trước thông minh. Ăn ngon mỗi ngày.</p></div><p>© 2026 SmartMeal AI · Căn tin xanh, campus xanh.</p></footer>}
createRoot(document.getElementById('root')).render(<App/>);
